### ISSUE TITLE
helm json status  dailed with Error: plugin "json" exited with error

### ISSUE THREAD

**Issue by hayorov** [Microsoft/helm-json-output#3]
Hi there,

got error during 
`⇒  helm json status cold-sheep`

```
/Users/allexx/.helm/cache/plugins/https-github.com-Microsoft-helm-json-output/index.js:76
  if (matches.length < 3) {
              ^

TypeError: Cannot read property 'length' of null
    at ExtractResources (/Users/allexx/.helm/cache/plugins/https-github.com-Microsoft-helm-json-output/index.js:76:15)
    at parseResponse (/Users/allexx/.helm/cache/plugins/https-github.com-Microsoft-helm-json-output/index.js:120:47)
    at execFile (/Users/allexx/.helm/cache/plugins/https-github.com-Microsoft-helm-json-output/index.js:146:20)
    at ChildProcess.exithandler (child_process.js:267:7)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
Error: plugin "json" exited with error
```

Info about environment:

```
⇒  helm version
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"
```

```
⇒  node --version
v8.9.1
```

**Comment by jldinh** [comment]
I can see it's an old issue, but in case anybody needs a workaround, the cause is that the regex expects a `NOTES:` section to be included in the helm output, and it is not included if there is no `NOTES.txt` in the chart templates. It results in the regex not matching at all.
So the workaround is just to add a `NOTES.txt`.
